In [1]:
import numpy as np

In [18]:
# Physical constants
pi = 3.14159265358979324 # Pi
h = 6.626070040E-34 # Planck's constant (Js)
k_b = 1.38064852E-23 # Boltzmann constant (J/K)
c = 299792458.0 # Speed of light (m/s)
mu_0 = 4.0*pi * 1E-7 # Vacuum permeability (H/m)
epsilon_0 = 1.0/(mu_0 * c**2) # Vacuum permittivity (F/m)
m_0 = 9.10938356E-31 # Free electron mass (kg)
q_0 = 1.6021766208E-19 # Standard charge (C)

# Defined constants
pre_fac_c = q_0**2/(4*pi*m_0*epsilon_0)
pre_fac_F = q_0/(4*pi*epsilon_0)
pre_fac_E = q_0/m_0


# Scale factors
time_scale = 1.0E-12
length_scale = 1.0E-9

# System parameters
d = 100.0*length_scale # Gap spacing (nm)
V = 2.0 # Voltage over gap (V)
delta_t = 0.25E-3*time_scale # Time step (ps)

#a_scale_c = time_scale**2/length_scale**3
#a_scale_E = time_scale**2/length_scale**3

# Electric field in system
E = np.array([0.0, 0.0, -V/d])

In [19]:
# Particle locations
# Electrons
R_1 = np.array([3.0, -10.0, 2.0])*length_scale
R_2 = np.array([-9.0, 26.0, 80.0])*length_scale

# Holes
R_3 = np.array([6.0, -24.0, 56.53])*length_scale

# Image charge particles

# Particle 1
# Above (Charge: Positive)
R_1a = R_1.copy()
R_1a[2] = 2.0*d - R_1a[2]

# Below (Charge: Positive)
R_1b = R_1.copy()
R_1b[2] = -1.0*R_1b[2]

# Particle 2
# Above (Charge: Positive)
R_2a = R_2.copy()
R_2a[2] = 2.0*d - R_2a[2]

# Below (Charge: Positive)
R_2b = R_2.copy()
R_2b[2] = -1.0*R_2b[2]

# Particle 3
# Above (Charge: Negative)
R_3a = R_3.copy()
R_3a[2] = 2.0*d - R_3a[2]

# Below (Charge: Negative)
R_3b = R_3.copy()
R_3b[2] = -1.0*R_3b[2]

In [20]:
# Acceleration particles 1 ----------------------------------------------------
# Acceleration from other particles
a_12 = +1.0*pre_fac_c * (R_1 - R_2) / np.linalg.norm(R_1 - R_2)**3
a_13 = -1.0*pre_fac_c * (R_1 - R_3) / np.linalg.norm(R_1 - R_3)**3

# Acceleration from image charge partners
# Self (-q*+q = -q**2)
a_11a = -1.0*pre_fac_c * (R_1 - R_1a) / np.linalg.norm(R_1 - R_1a)**3
a_11b = -1.0*pre_fac_c * (R_1 - R_1b) / np.linalg.norm(R_1 - R_1b)**3
# Other electron (-q*+q = -q**2)
a_12a = -1.0*pre_fac_c * (R_1 - R_2a) / np.linalg.norm(R_1 - R_2a)**3
a_12b = -1.0*pre_fac_c * (R_1 - R_2b) / np.linalg.norm(R_1 - R_2b)**3
# Other hole (-q*-q = +q**2)
a_13a = +1.0*pre_fac_c * (R_1 - R_3a) / np.linalg.norm(R_1 - R_3a)**3
a_13b = +1.0*pre_fac_c * (R_1 - R_3b) / np.linalg.norm(R_1 - R_3b)**3

# Acceleration from the electric field in the diode
a_1E = -1.0*pre_fac_E * E

# Total acceleration
a_1 = a_12 + a_13 + a_11a + a_11b + a_12a + a_12b + a_13a + a_13b + a_1E

print('Particle 1')
print(a_1)

Particle 1
[-5.56478062e+14  8.31621767e+14 -1.22151251e+19]


In [21]:
# Acceleration particles 2 -----------------------------------------------------
# Acceleration from other particles
a_21 = +1.0*pre_fac_c * (R_2 - R_1) / np.linalg.norm(R_2 - R_1)**3
a_23 = -1.0*pre_fac_c * (R_2 - R_3) / np.linalg.norm(R_2 - R_3)**3

# Acceleration from image charge partners
# Other electron (-q*+q = -q**2)
a_21a = -1.0*pre_fac_c * (R_2 - R_1a) / np.linalg.norm(R_2 - R_1a)**3
a_21b = -1.0*pre_fac_c * (R_2 - R_1b) / np.linalg.norm(R_2 - R_1b)**3
# Self (-q*+q = -q**2) 
a_22a = -1.0*pre_fac_c * (R_2 - R_2a) / np.linalg.norm(R_2 - R_2a)**3
a_22b = -1.0*pre_fac_c * (R_2 - R_2b) / np.linalg.norm(R_2 - R_2b)**3
# Other hole (-q*-q = +q**2)
a_23a = +1.0*pre_fac_c * (R_2 - R_3a) / np.linalg.norm(R_2 - R_3a)**3
a_23b = +1.0*pre_fac_c * (R_2 - R_3b) / np.linalg.norm(R_2 - R_3b)**3

# Acceleration from the electric field in the diode
a_2E = -1.0*pre_fac_E * E

a_2 = a_21 + a_23 + a_21a + a_21b + a_22a + a_22b + a_23a + a_23b + a_2E

print('Particle 2')
print(a_2)

Particle 2
[ 1.32595601e+16 -4.38454784e+16  3.63425018e+18]


In [22]:
# Acceleration particles 3 -----------------------------------------------------
# Acceleration from other particles
a_31 = -1.0*pre_fac_c * (R_3 - R_1) / np.linalg.norm(R_3 - R_1)**3
a_32 = -1.0*pre_fac_c * (R_3 - R_2) / np.linalg.norm(R_3 - R_2)**3

# Acceleration from image charge partners
# Other electron (+q*+q = +q**2)
a_31a = +1.0*pre_fac_c * (R_3 - R_1a) / np.linalg.norm(R_3 - R_1a)**3
a_31b = +1.0*pre_fac_c * (R_3 - R_1b) / np.linalg.norm(R_3 - R_1b)**3
# Other electron (+q*+q = +q**2) 
a_32a = +1.0*pre_fac_c * (R_3 - R_2a) / np.linalg.norm(R_3 - R_2a)**3
a_32b = +1.0*pre_fac_c * (R_3 - R_2b) / np.linalg.norm(R_3 - R_2b)**3
# Self (+q*-q = -q**2) 
a_33a = -1.0*pre_fac_c * (R_3 - R_3a) / np.linalg.norm(R_3 - R_3a)**3
a_33b = -1.0*pre_fac_c * (R_3 - R_3b) / np.linalg.norm(R_3 - R_3b)**3

# Acceleration from the electric field in the diode
a_3E = +1.0*pre_fac_E * E

a_3 = a_31 + a_32 + a_31a + a_31b + a_32a + a_32b + a_33a + a_33b + a_3E

print('Particle 3')
print(a_3)

Particle 3
[-1.27030820e+16  4.30138567e+16 -3.51190760e+18]


In [24]:
# Electric field at position ---------------------------------------------------
R_4 = np.array([-4.55, -2.34, 96.44])*length_scale

# From real particles
E_1 = -1.0*pre_fac_F * (R_4 - R_1) / np.linalg.norm(R_4 - R_1)**3
E_2 = -1.0*pre_fac_F * (R_4 - R_2) / np.linalg.norm(R_4 - R_2)**3
E_3 = +1.0*pre_fac_F * (R_4 - R_3) / np.linalg.norm(R_4 - R_3)**3

# From image charge particles
# Electron 1
E_1a = +1.0*pre_fac_F * (R_4 - R_1a) / np.linalg.norm(R_4 - R_1a)**3
E_1b = +1.0*pre_fac_F * (R_4 - R_1b) / np.linalg.norm(R_4 - R_1b)**3
# Electron 2
E_2a = +1.0*pre_fac_F * (R_4 - R_2a) / np.linalg.norm(R_4 - R_2a)**3
E_2b = +1.0*pre_fac_F * (R_4 - R_2b) / np.linalg.norm(R_4 - R_2b)**3
# Hole 1
E_3a = -1.0*pre_fac_F * (R_4 - R_3a) / np.linalg.norm(R_4 - R_3a)**3
E_3b = -1.0*pre_fac_F * (R_4 - R_3b) / np.linalg.norm(R_4 - R_3b)**3

print('pre_fac_F = ', pre_fac_F)
print('diff = ', (R_4 - R_1))
print('r = ', np.linalg.norm(R_4 - R_1))

E_tot = E_1 + E_2 + E_3 + E_1a + E_1b + E_2a + E_2b + E_3a + E_3b + E
print('Electric field')
print(E_tot)

pre_fac_F =  1.4399645351950547e-09
diff =  [-7.550e-09  7.660e-09  9.444e-08]
r =  9.50504692255646e-08
Electric field
[  -102526.05673208    421022.84663293 -20456407.74487634]
